import Head from "next/head";
import Footer from "./footer/footer";
import Menu from "./menu/menu";
import ShoppingCart from "./shoppingCart";
// import { useAppContext } from "@/components/stateWrapper";

export const Layout = ({ children, title }) => {
    // const { isMenuOpen } = useAppContext();
    const titleTab = title ? title : "";
    return (
        <>
            <Head>
                <title>{`Tienda ${titleTab}`}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <section className="container mx-auto px-0 sm:px-2">
                {/* <div className={`${isMenuOpen ? "fixed" : ""}`}> */}
                <ShoppingCart />
                {/* </div> */}
                {children}
            </section>
            <Footer />
        </>
    );
};
