import Head from "next/head";
import Footer from "./footer/footer";
import Menu from "./menu";

export const Layout = ({ children, title }) => {
    return (
        <>
            <Head>
                <title>Tienda {title ? `${title}` : ""}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <section className="container mx-auto px-0 sm:px-2 ">
                {children}
            </section>
            <Footer />
        </>
    );
};
